from pydantic import BaseModel, Field
from typing import Optional

class ChatRequest(BaseModel):
    query: str = Field(..., description="User's query for the chatbot")

class ChatResponse(BaseModel):
    response: str = Field(..., description="Response generated by the chatbot")

class ChatHistoryResponse(BaseModel):
    date: str = Field(..., description="Date of the chat history in 'YYYY-MM-DD' format")

class ConversationInput(BaseModel):
    conversation_history: list[dict]